### ISSUE TITLE
Use 'file' id over 'image'

### ISSUE THREAD

**Issue by antiops** [DoubleHub/cyberdrop-downloader#1]
Ive noticed the 'file' id has a link that responds better. Its usually faster and rarely errors out like the other one

normal : https://f.cyberdrop.cc/file.ext
file id : https://f.cyberdrop.cc/s/file.ext

**Comment by giovanni-orciuolo** [comment]
Nice! Didn't know about that link. I will change it now and commit

**Comment by giovanni-orciuolo** [comment]
Done! Thanks a lot!!!
